uipath-service/main/default/objects/Case/fields/Case_Web_Form_Region__c.field-meta.xml
<CustomField>
    <fullName>Case_Web_Form_Region__c</fullName>
    <label>Case Web Form Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Cloud Enterprise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/objects/Case/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <label>Product Component</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academic Alliance</fullName>
            </value>
            <value>
                <fullName>Academy</fullName>
            </value>
            <value>
                <fullName>Agent Desktop</fullName>
                <label>UiPath Assistant</label>
            </value>
            <value>
                <fullName>AI Fabric</fullName>
            </value>
            <value>
                <fullName>Apps</fullName>
                <label>Action Center</label>
            </value>
            <value>
                <fullName>Attended browser embedding SDK</fullName>
            </value>
            <value>
                <fullName>Automation Ready Programs</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Cloud Platform</fullName>
                <label>Automation Cloud</label>
            </value>
            <value>
                <fullName>Connect Enterprise</fullName>
                <label>Automation Hub</label>
            </value>
            <value>
                <fullName>Data Service</fullName>
            </value>
            <value>
                <fullName>Document Understanding</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>IT Automation</fullName>
            </value>
            <value>
                <fullName>Learning Platform Inquiries</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
                <label>License</label>
            </value>
            <value>
                <fullName>Orchestrator</fullName>
            </value>
            <value>
                <fullName>Orchestrator Mobile</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner Product</fullName>
            </value>
            <value>
                <fullName>Partner Training</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Process Gold</fullName>
                <label>Process Mining</label>
            </value>
            <value>
                <fullName>Robot</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Studio X</fullName>
            </value>
            <value>
                <fullName>Task Capture</fullName>
            </value>
            <value>
                <fullName>Task Mining</fullName>
            </value>
            <value>
                <fullName>Test Manager</fullName>
            </value>
            <value>
                <fullName>UiPath Go</fullName>
                <label>UiPath Connect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/classes/CaseAssignQueueFunction.cls
public with sharing class CaseAssignQueueFunction implements SObjectToSObjectFunction {
  public CaseAssignQueueFunction() {
  }

  public SObject apply(Case newCase) {
    if (newCase.Origin == 'Community') {
      if (newCase.RecordTypeId == CaseMetadata.IncidentRecordType) {
        if (newCase.Related_To__c == 'Studio') {
          newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('Studio_Queue');
        } else if (CaseMetadata.SupportedProducts.contains(newCase.Related_To__c)) {
          newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('Product_Support_Queue');
        } else if (newCase.Related_To__c == 'Orchestrator') {
          newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('Orchestrator_Queue');
        } else if (newCase.Related_To__c == 'Robot') {
          newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('Robot_Queue');
        } else if (newCase.Related_To__c == 'Partner Product') {
          newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('Partner_Product');
        }
      } else if (
        newCase.RecordTypeId == CaseMetadata.JapanIncidentRecordType &&
        newCase.Case_Web_Form_Region__c == 'Japan'
      ) {
        if (newCase.Related_To__c == 'Studio') {
          newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('Japan_Studio_Queue');
        } else if (CaseMetadata.SupportedProducts.contains(newCase.Related_To__c)) {
          newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('Japan_Product_Support_Queue');
        } else if (newCase.Related_To__c == 'Orchestrator') {
          newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('Japan_Orchestrator_Queue');
        } else if (newCase.Related_To__c == 'Robot') {
          newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('Japan_Robot_Queue');
        } else if (newCase.Related_To__c == 'Partner Product') {
          newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('Japan_Partner_Product');
        } else if (newCase.Related_To__c == 'Academy') {
          newCase.RecordTypeId = CaseMetadata.JapanAcademyRecordType;
          newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('Japan_Academy_Queue');
        } else if (newCase.Related_To__c == 'Cloud Platform') {
          newCase.RecordTypeId = CaseMetadata.JapanLicensingRecordType;
          newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('Japan_Licensing_Queue');
        }
      } else if (newCase.RecordTypeId == CaseMetadata.JapanEngagementRequestRecordType) {
        newCase.OwnerId = CaseMetadata.QueueNameToIdMap.get('ER_Queue');
      }
    } else if (newCase.Origin == null) {
      newCase.Origin = CaseMetadata.ORIGIN_INTERNAL;
    }
    return newCase;
  }

  public SObject apply(SObject record) {
    return apply((Case) record);
  }

  public static void deriveOwners(List<SObject> cases) {
    Collection.of(cases)
      .filter(
        Match.field(Case.RecordTypeId)
          .isIn(
            new Set<String>{
              CaseMetadata.IncidentRecordType,
              CaseMetadata.JapanIncidentRecordType,
              CaseMetadata.JapanEngagementRequestRecordType
            }
          )
      )
      .mapAll(new CaseAssignQueueFunction());
  }
}