uipath-service/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

uipath-service/main/default/objects/Case/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GMT+00:00  Greenwich Mean Time</fullName>
            </value>
            <value>
                <fullName>GMT+00:00  Western European Time</fullName>
            </value>
            <value>
                <fullName>GMT+01:00  Central European Time</fullName>
            </value>
            <value>
                <fullName>GMT+02:00  Eastern European Time</fullName>
            </value>
            <value>
                <fullName>GMT+02:00  Israel Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT+02:00  South Africa Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT+03:00  Arabian Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT+03:00  East Africa Time</fullName>
            </value>
            <value>
                <fullName>GMT+03:00  Further-eastern European Time</fullName>
            </value>
            <value>
                <fullName>GMT+03:30  Iran Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT+04:00  Georgia Time</fullName>
            </value>
            <value>
                <fullName>GMT+04:00  Gulf Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT+04:00  Moscow Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT+04:30  Afghanistan Time</fullName>
            </value>
            <value>
                <fullName>GMT+05:00  Pakistan Time</fullName>
            </value>
            <value>
                <fullName>GMT+05:00  Uzbekistan Time</fullName>
            </value>
            <value>
                <fullName>GMT+05:30  India Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT+05:45  Nepal Time</fullName>
            </value>
            <value>
                <fullName>GMT+06:00  Bangladesh Time</fullName>
            </value>
            <value>
                <fullName>GMT+06:00  Yekaterinburg Time</fullName>
            </value>
            <value>
                <fullName>GMT+06:30  Myanmar Time</fullName>
            </value>
            <value>
                <fullName>GMT+07:00  Indochina Time</fullName>
            </value>
            <value>
                <fullName>GMT+07:00  Western Indonesia Time</fullName>
            </value>
            <value>
                <fullName>GMT+08:00  Australian Western Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT+08:00  China Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT+08:00  Hong Kong Time</fullName>
            </value>
            <value>
                <fullName>GMT+08:00  Malaysia Time</fullName>
            </value>
            <value>
                <fullName>GMT+08:00  Philippine Time</fullName>
            </value>
            <value>
                <fullName>GMT+08:00  Singapore Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT+08:00  Taipei Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT-04:00  Atlantic Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT-05:00  Eastern Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT-06:00  Central Standard Time</fullName>
            </value>
            <value>
                <fullName>GMT-08:00  Pacific Standard Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/classes/CaseInsertBusinessHoursFunction.cls
/**
 * TODO: To refactor
 */
public with sharing class CaseInsertBusinessHoursFunction implements SObjectToSObjectFunction {
    //Map to Store  Country With Their BusinessHours
    Map<String, Id> mapOfCounBH = new Map<String, Id>();

  public CaseInsertBusinessHoursFunction(List<Case> cases) {

    List<BusinessHours> lstOfBH = new List<BusinessHours>([SELECT Id, Name FROM BusinessHours WHERE IsActive = true]);
    System.debug('updateBusinessHours @35' + cases);

    //Putting value of BusinessHours in Map
    for (BusinessHours eachBH : lstOfBH) {
      mapOfCounBH.put(eachBH.Name, eachBH.Id);
    }
  }

  public SObject apply(Case eachCase) {
    if (eachCase.Priority == 'Urgent' || eachCase.Priority == 'High') {
      eachCase.BusinessHoursId = mapOfCounBH.get('DefaultBusinessHours');
    } else if (eachCase.Priority == 'Medium' || eachCase.Priority == 'Low' && (eachCase.Country__c != null)) {
      if (eachCase.Country__c == 'United States') {
        if (eachCase.Time_Zone__c != null) {
          if (
            eachCase.Time_Zone__c == 'GMT-05:00  Eastern Standard Time' ||
            eachCase.Time_Zone__c == 'GMT-04:00  Eastern Standard Time'
          ) {
            eachCase.BusinessHoursId = mapOfCounBH.get('US(EST) Business Hours(9hrs)');
          } else if (
            eachCase.Time_Zone__c == 'GMT-06:00  Central Standard Time' ||
            eachCase.Time_Zone__c == 'GMT-05:00  Central Standard Time'
          ) {
            eachCase.BusinessHoursId = mapOfCounBH.get('US(CST) Business Hours(9hrs)');
          } else if (
            eachCase.Time_Zone__c == 'GMT-08:00  Pacific Standard Time' ||
            eachCase.Time_Zone__c == 'GMT-07:00  Pacific Standard Time'
          ) {
            eachCase.BusinessHoursId = mapOfCounBH.get('US(PST) Business Hours(9hrs)');
          } else if (
            eachCase.Time_Zone__c == 'GMT-04:00  Atlantic Standard Time' ||
            eachCase.Time_Zone__c == 'GMT-05:00  Atlantic Standard Time'
          ) {
            eachCase.BusinessHoursId = mapOfCounBH.get('US(AST) Business Hours(9hrs)');
          } else {
            eachCase.BusinessHoursId = mapOfCounBH.get('US(CST) Business Hours(9hrs)');
          }
        } else {
          eachCase.BusinessHoursId = mapOfCounBH.get('US(CST) Business Hours(9hrs)');
        }
      } else if (mapOfCounBH.containsKey(eachCase.Country__c)) {
        eachCase.BusinessHoursId = mapOfCounBH.get(eachCase.Country__c);
      } else {
        //eachCase.addError('Country not found');
      }
    } else {
      //eachCase.addError('Country not found');
    }
    return eachCase;
  }

  public SObject apply(SObject record) {
    return apply((Case) record);
  }

  public static void deriveBusinessHoursOnInsert(List<Case> records) {
    Collection.of(records).mapSome(Match.field(Case.Priority).hasValue(), new CaseInsertBusinessHoursFunction(records));
  }
}